#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/AspellGUI
find AspellGUI -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/AspellGUI/makepkg
mv /tmp/AspellGUI /tmp/AspellGUI-${VERSION}

cd /tmp/AspellGUI-${VERSION}

./remakesourcelist
aclocal
autoheader
touch NEWS README AUTHORS ChangeLog
automake --add-missing --copy
autoconf

rm -rf ./autom4te.cache
rm ./compile ./missing ./COPYING ./AUTHORS ./NEWS ./README
cd ..

tar -czvf AspellGUI-${VERSION}.tar.gz AspellGUI-${VERSION}
rm -r /tmp/AspellGUI-${VERSION}