.\" aspellgui
.TH "aspellgui" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
aspellgui \- manual page for aspellgui 0.0.0
.SH "SYNOPSIS"
.B aspellgui
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
aspellgui
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
